export default {
	auth: state => state.auth.token,
	authKey: state => state.auth.authKey,
	authToken: state => state.auth.authToken,
	userInfo: state => state.auth.userInfo,
	sdkConfig: state => state.auth.config,
	im: state => state.nim.nimInstance,
	sessions: state => state.nim.sessions,
	chatMessages: state => state.nim.chatMessages,
	users: state => state.nim.users,
	room: state => state.room.roomInstance,
	unread: state => state.nim.unread,
	userAccount: state => state.auth.userAccount,
	verifyCode: state => state.auth.verifyCode,
	phone: state => state.auth.phone,
	nick: state => state.auth.nick,
	headIcon: state => state.auth.headIcon,
	phoneLoginTag: state => state.auth.phoneLoginTag,
	networkType: state => state.platform.networkType,
	availWidth: state => state.platform.availWidth,
	availHeight: state => state.platform.availHeight,
	ratio: state => state.platform.ratio,
	imgPostfix: state => state.platform.imgPostfix,
	modifyName: state => state.auth.modifyName,
};
