export default {
	login: 'LOGIN',
	logout: 'LOGIN_OUT',
	setUserInfo: 'SET_USER_INFO',
	setAuthKey: 'SET_AUTH_KEY',
	setExpire: 'SET_EXPIRE',
	setNim: 'SET_NIM',
	setRoom: 'SET_ROOM',
	setSessions: 'SET_SESSIONS',
	setConfig: 'SET_CONFIG',
	setCurrent: 'SET_CURRENT',
	setChatMessages: 'SET_CHAT_MESSAGES',
	setUsers: 'SET_USERS',
	setUserAccount: 'SET_USER_ACCOUNT',
	setVerifyCode: 'SET_VERIFY_CODE',
	setPhone: 'SET_PHONE',
	setPhoneLoginTag: 'SET_PHONE_LOGIN_TAG',
	setNetworkType: 'SET_NETWORK_TYPE',
	setModifyName: 'SET_MODIFY_NAME',
};
